### ISSUE TITLE
06.섹션 컴퍼넌트 구조화하기

### ISSUE THREAD

**Issue by Jae-hong-lee** [Jae-hong-lee/youtube-clone#4]
![Image](https://github.com/Jae-hong-lee/youtube-clone/assets/72030487/fc028223-de97-4501-91aa-85ab3896ac46)

전체 레이아웃 만들기
완성된 페이지를 확인해 보면 전체적인 구조는 `header`, `main`, `footer` 3단 구조로 되어있다.

페이지를 만들었으니 각 페이지의 섹션을 만들었다.  ➡️ App.js 페이지에서 셋팅
>리액트에서는 컴퍼넌트라고 얘기하죠! 

기존 파일에 컴퍼넌트를 추가 후 CSS도 같이 설정해주자.
section 폴더에 `layout.scss` 생성, `style.scss` 에 section에 layout 부분 추가 후 
css 코드 작성해주면 끝
```css
// layout.scss
#header {
    position: fixed;
    left: 0;
    top: 0;
    width: 260px;
    height: 100%;
    z-index: 10000;
    background-color: #000;
}
#main {
    max-width: 2000px;
    min-height: 100vh;
    margin: 0 auto;
    padding-left: 260px;
    background-color: #111;
}
#footer {
    text-align: center;
    background-color: #333;
    padding: 20px 20px 20px 260px;
} 
```
